title: Page

# bluepring for the default page

pages: true
options:
  preview: true
  status: true
  template: false
  url: true
  delete: true

files:
  fields:
    caption:
      label: Bildbeschreibung
      type: textarea
    copyright:
      label: Copyright
      type: text
      default: Archiv der Moderne

fields:
  title:
    label:
      de: Überschrift
      en: Title
    type:  text

  text:
    label: Text
    type:  textarea

  text_en:
    label: Text (English)
    type:  textarea