title: Site

# blueprint for the site in general

pages:
  limit: 50

fields:
  title:
    label: Name
    type:  text

  description:
    label: Beschreibung
    type:  textarea

  imprint_url:
    label: Link zu externem Impressum (zB. Uni-Seite)
    type: url
